project:
  name: quickstart-armory-enterprise
  shorten_stack_name: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambda: true
  template: templates/spinnaker-entrypoint-new-vpc.template.yml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  armory-3az-defaults:
    parameters:
      KeyPairName: cikey
      RemoteAccessCIDR: 10.0.0.0/0
      DBUserPassword: P!$[taskcat_genpass_12A]
      DBMasterUserPassword: P!$[taskcat_genpass_12A]
      AvailabilityZones: $[taskcat_genaz_3]
      NumberOfAZs: 3
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
    - us-west-2
    - us-east-1
