AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploys the Armory Enterprise operator and service onto EKS (qs-1rphnhskl)."
Metadata:
  cfn-lint: { config: { ignore_checks: [W9004, W9003, W9002, W9006, E1010] }}
Parameters:
  KubeClusterName:
    Default: ""
    Type: String
  QSS3BucketName:
    Type: String
  QSS3BucketRegion:
    Type: String
  QSS3KeyPrefix:
    Type: String
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  SpinnakerOpDeployment:
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3001 ] } } }
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName 
      Namespace: "spinnaker-operator"
      Url: !Sub
        - 's3://${S3Bucket}/${QSS3KeyPrefix}manifests/operator.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
#      From - Url: https://raw.githubusercontent.com/mcgonagle/qas/main/operator.yaml
  SpinnakerService:
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3001 ] } } }
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName 
      Namespace: "spinnaker"
      Url: !Sub
        - 's3://${S3Bucket}/${QSS3KeyPrefix}manifests/spinnaker.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
#      From - Url: https://raw.githubusercontent.com/mcgonagle/qas/main/spinnaker.yaml
    DependsOn: SpinnakerOpDeployment
  IngressDeployment:
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3001 ] } } }
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "ingress-nginx"
      Url: !Sub
        - 's3://${S3Bucket}/${QSS3KeyPrefix}manifests/ingress.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
#      From - Url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/aws/deploy.yaml
    DependsOn: SpinnakerService
  GetELBDetail:
    DependsOn: IngressDeployment
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3001 ] } } }
    Type: AWSQS::Kubernetes::Get
    Properties:
      ClusterName: !Ref KubeClusterName
      Name: "service/spin-deck"
      Namespace: "spinnaker"
      JsonPath: "{.status.loadBalancer.ingress[0].hostname}"
#Outputs:
#  SpinDeckDNSName:
 #   Value: !GetAtt "GetELBDetail.Response"
